spring.application.name=Proyecto Final ACM

spring.datasource.url=jdbc:postgresql://localhost:5432/hotelACM
spring.datasource.username=postgres
spring.datasource.password=juandavid12
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true